import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Kurt Oswill McCarver",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${poppins.variable} bg-[#080c14] antialiased font-sans 
                px-4 sm:px-6 md:px-10 lg:px-[50px]`}
            >
                <Navbar />
                <main className="w-full">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
